### ISSUE TITLE
Bug: maplibregl-ctrl-bottom-right styles are broken since v1.0.0

### ISSUE THREAD

**Issue by dmestudent** [mapcomponents/react-map-components-maplibre#163] opened 2024-02-21 10:35 UTC
@mapcomponents/react-maplibre version: >=1.0.0

## Steps To Reproduce

1. Follow the getting started with your template guide
2. Start the example after installing dependencies and visit the page

## The current behavior

Styles are missing for  maplibregl-ctrl-bottom-right causing an unstyled container rendered below the map

![image](https://github.com/mapcomponents/react-map-components-maplibre/assets/57351574/107176d7-6c11-4520-9ce5-0b2a652f0f15)

## The expected behavior

maplibregl-ctrl-bottom-right is styled properly and sits as an overlay on the map

![image](https://github.com/mapcomponents/react-map-components-maplibre/assets/57351574/208882bf-dfd0-4498-8dd4-6bf5ce5f9dfe)

I manually checked the last released versions and this error started appearing since version 1.0.0

Best regards

**Comment by dBitech** [comment] 2024-02-21 15:48
There were some changes to the default handling of attribution in Maplibre 4.0  perhaps this is why

**Comment by cioddi** [comment] 2024-02-22 09:08
Thank you for the issue, I also noticed this when setting up a new project yesterday. 
We will take a look at it and fix this.

**Comment by cioddi** [comment] 2024-02-22 09:15
I already found the cause.
In the versions before 1.0.0 we imported maplibre-gl.css in the MapLibreMap component. That was commented out to rule it out as a cause for the failing bundler command after the major rollup release upgrade.

We will put this back in in the next release. 
Until then a quick fix would be to add this line to your application `import 'maplibre-gl/dist/maplibre-gl.css';`

**Comment by cioddi** [comment] 2024-02-22 09:53
Fixed in version 1.0.3

The changes to the attribution API in MapLibre 4.0 involve that is is enabled by default and the removal of customAttribution prop from AttributionControl. https://github.com/maplibre/maplibre-gl-js/blob/main/CHANGELOG.md#400

**Closed by cioddi** 2024-02-22 09:53 UTC
